In [ ]:
# ASG Airlines – End-to-End Data Engineering Pipeline

## Project Objective
###To build a reliable data engineering pipeline for airline operational data by performing data ingestion, data quality checking, cleaning, transformation, validation, KPI generation, and preparation of data for Power BI.""""

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Load all sheets from the Excel file

file_path = "/content/UseCase - Airlines.xlsx"

flights = pd.read_excel(file_path, sheet_name="flights")
bookings = pd.read_excel(file_path, sheet_name="bookings")
payments = pd.read_excel(file_path, sheet_name="payments")
passengers = pd.read_excel(file_path, sheet_name="passengers")

print("Data loaded successfully!")
print()
print("Flights:", flights.shape)
print("Bookings:", bookings.shape)
print("Payments:", payments.shape)
print("Passengers:", passengers.shape)

Data loaded successfully!

Flights: (1020, 7)
Bookings: (1000, 9)
Payments: (1000, 4)
Passengers: (1039, 9)

In [ ]:
#Display column names

print("FLIGHTS COLUMNS:")
print(flights.columns.tolist())
print("\n----- FLIGHTS -----")
display(flights.head())

print("\nBOOKINGS COLUMNS:")
print(bookings.columns.tolist())
print("\n----- BOOKINGS -----")
display(bookings.head())

print("\nPAYMENTS COLUMNS:")
print(payments.columns.tolist())
print("\n----- PAYMENTS -----")
display(payments.head())

print("\nPASSENGERS COLUMNS:")
print(passengers.columns.tolist())
print("\n----- PASSENGERS -----")
display(passengers.head())

FLIGHTS COLUMNS:
['flight_id', 'airline', 'source', 'destination', 'departure_time', 'arrival_time', 'duration']

----- FLIGHTS -----

,flight_id,airline,source,destination,departure_time,arrival_time,duration
0,SJ010,SpiceJet,CCU,MAA,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701,02:54:00
1,AI155,Air India,BOM,CCU,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703,01:48:00
2,UK094,Vistara,BOM,CCU,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702,01:45:00
3,AI245,Air India,BOM,CCU,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704,02:36:00
4,AI192,Air India,MAA,BOM,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703,04:59:00

BOOKINGS COLUMNS:
['booking_id', 'passenger_id', 'flight_id', 'booking_date', 'status', 'passport_number', 'seat_number', 'emergency_contact_name', 'emergency_contact_phone']

----- BOOKINGS -----

,booking_id,passenger_id,flight_id,booking_date,status,passport_number,seat_number,emergency_contact_name,emergency_contact_phone
0,B1000,P1591,AI192,2025-06-14 11:37:36.951,CANCELLED,P1945887,3D,Isaac Bakshi,+91-6478475128
1,B1001,P1803,6F026,2025-11-02 11:37:36.951,CANCELLED,L3482012,18A,Anvi Konda,+91-6647078662
2,B1002,P1083,SJ010,2025-08-25 11:37:36.951,CANCELLED,G8507659,30C,Udant Dewan,+91-8405938220
3,B1003,P1364,AI069,2025-12-30 11:37:36.951,CONFIRMED,M0891776,33A,Harsh Chahal,+91-6264636839
4,B1004,P1885,UK003,2025-10-02 11:37:36.951,PENDING,N5742231,25C,Pahal Balay,+91-9336478266

PAYMENTS COLUMNS:
['payment_id', 'booking_id', 'amount', 'payment_method']

----- PAYMENTS -----

  payment_id booking_id    amount payment_method
0    PAY1000      B1116   9883.49     NETBANKING
1    PAY1001      B1738   8457.96     NETBANKING
2    PAY1002      B1873   6495.37            UPI
3    PAY1003      B1914   5079.38     NETBANKING
4    PAY1004      B1967  12518.31           CARD

PASSENGERS COLUMNS:
['passenger_id', 'first_name', 'last_name', 'age', 'gender', 'email', 'phone', 'aadhaar_id', 'date_of_birth']

----- PASSENGERS -----

,passenger_id,first_name,last_name,age,gender,email,phone,aadhaar_id,date_of_birth
0,P1000,Vivaan,Chatterjee,52,F,vivaan.chatterjee@gmail.com,+91-6896233790,433218196001,1974-04-08
1,P1001,Krishna,Reddy,15,M,krishna.reddy@hotmail.com,+91-6702632297,386379402654,2011-03-07
2,P1002,Myra,Naidu,72,M,myra.naidu@outlook.com,+91-6199585092,615594078161,1954-09-10
3,P1003,Myra,Mishra,61,F,myra.mishra@hotmail.com,+91-8719927151,310341316475,1965-03-12
4,P1004,Saanvi,Banerjee,21,M,saanvi.banerjee@outlook.com,+91-7819595113,419283276483,2005-11-11

In [ ]:
#Check data types and basic information

print("\n---- FLIGHTS ----")
flights.info()

print("\n---- BOOKINGS -----")
bookings.info()

print("\n---- PAYMENTS ----")
payments.info()

print("\n---- PASSENGERS ----")
passengers.info()

---- FLIGHTS ----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   flight_id       1020 non-null   object
 1   airline         979 non-null    object
 2   source          1020 non-null   object
 3   destination     1020 non-null   object
 4   departure_time  1020 non-null   datetime64[ns]
 5   arrival_time    1020 non-null   datetime64[ns]
 6   duration        1020 non-null   object
dtypes: datetime64[ns](2), object(5)
memory usage: 55.9+ KB

---- BOOKINGS -----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   booking_id               1000 non-null   object
 1   passenger_id             1000 non-null   object
 2   flight_id                1000 non-null   object
 3   booking_date             1000 non-null   datetime64[ns]
 4   status                   955 non-null    object
 5   passport_number          1000 non-null   object
 6   seat_number              1000 non-null   object
 7   emergency_contact_name   1000 non-null   object
 8   emergency_contact_phone  1000 non-null   object
dtypes: datetime64[ns](1), object(8)
memory usage: 70.4+ KB

---- PAYMENTS ----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      1000 non-null   object
 1   booking_id      1000 non-null   object
 2   amount          952 non-null    object
 3   payment_method  1000 non-null   object
dtypes: object(4)
memory usage: 31.4+ KB

---- PASSENGERS ----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1039 entries, 0 to 1038
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   passenger_id   1039 non-null   object
 1   first_name     1039 non-null   object
 2   last_name      1029 non-null   object
 3   age            1039 non-null   int64
 4   gender         1039 non-null   object
 5   email          1039 non-null   object
 6   phone          1039 non-null   object
 7   aadhaar_id     1039 non-null   int64
 8   date_of_birth  1039 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(6)
memory usage: 73.2+ KB

In [ ]:
#Check missing values

print("Missing values in FLIGHTS:")
print(flights.isnull().sum())

print("\nMissing values in BOOKINGS:")
print(bookings.isnull().sum())

print("\nMissing values in PAYMENTS:")
print(payments.isnull().sum())

print("\nMissing values in PASSENGERS:")
print(passengers.isnull().sum())

Missing values in FLIGHTS:
flight_id          0
airline           41
source             0
destination        0
departure_time     0
arrival_time       0
duration           0
dtype: int64

Missing values in BOOKINGS:
booking_id                  0
passenger_id                0
flight_id                   0
booking_date                0
status                     45
passport_number             0
seat_number                 0
emergency_contact_name      0
emergency_contact_phone     0
dtype: int64

Missing values in PAYMENTS:
payment_id         0
booking_id         0
amount            48
payment_method     0
dtype: int64

Missing values in PASSENGERS:
passenger_id      0
first_name        0
last_name        10
age               0
gender            0
email             0
phone             0
aadhaar_id        0
date_of_birth     0
dtype: int64

In [ ]:
#Check exact duplicate rows

print("Duplicate rows in FLIGHTS:", flights.duplicated().sum())
print("Duplicate rows in BOOKINGS:", bookings.duplicated().sum())
print("Duplicate rows in PAYMENTS:", payments.duplicated().sum())
print("Duplicate rows in PASSENGERS:", passengers.duplicated().sum())

Duplicate rows in FLIGHTS: 15
Duplicate rows in BOOKINGS: 0
Duplicate rows in PAYMENTS: 0
Duplicate rows in PASSENGERS: 0

In [ ]:
#Check important categorical values

print("Airlines:")
print(flights["airline"].value_counts(dropna=False))

print("\nBooking Status:")
print(bookings["status"].value_counts(dropna=False))

print("\nPayment Methods:")
print(payments["payment_method"].value_counts(dropna=False))

Airlines:
airline
IndiGo       249
SpiceJet     240
Air India    236
Vistara      223
NaN           41
UNKNOWN       31
Name: count, dtype: int64

Booking Status:
status
CONFIRMED    320
CANCELLED    314
PENDING      291
NaN           45
INVALID       30
Name: count, dtype: int64

Payment Methods:
payment_method
UPI           358
CARD          329
NETBANKING    313
Name: count, dtype: int64

In [ ]:
#Check duplicate IDs

print("Duplicate flight IDs:",
      flights["flight_id"].duplicated().sum())
print("\n ---- DUPLICATE FLIGHT IDs ----")
print(flights[flights["flight_id"].duplicated(keep=False)].sort_values("flight_id"))

print("Duplicate booking IDs:",
      bookings["booking_id"].duplicated().sum())

print("Duplicate passenger IDs:",
      passengers["passenger_id"].duplicated().sum())

print("Duplicate payment IDs:",
      payments["payment_id"].duplicated().sum())
print("\n---- DUPLICATE PASSENGER IDs -----")
print(passengers[passengers["passenger_id"].duplicated(keep=False)].sort_values("passenger_id"))

Duplicate flight IDs: 16

 ---- DUPLICATE FLIGHT IDs ----
    flight_id    airline source destination          departure_time  \
253     6F250    UNKNOWN    DEL         BLR 2026-04-20 03:26:41.701
270     6F250    UNKNOWN    CCU         BLR 2026-04-20 02:23:41.702
550     AI020        NaN    BOM         BLR 2026-04-19 03:53:41.701
549     AI020        NaN    BOM         BLR 2026-04-19 03:53:41.701
141     AI031  Air India    DEL         MAA 2026-04-20 13:05:41.701
142     AI031  Air India    DEL         MAA 2026-04-20 13:05:41.701
599     AI043  Air India    CCU         DEL 2026-04-19 00:28:41.701
598     AI043  Air India    CCU         DEL 2026-04-19 00:28:41.701
603     AI070  Air India    CCU         DEL 2026-04-19 00:05:41.702
602     AI070  Air India    CCU         DEL 2026-04-19 00:05:41.702
83      AI242    UNKNOWN    BLR         CCU 2026-04-20 16:41:41.704
84      AI242    UNKNOWN    BLR         CCU 2026-04-20 16:41:41.704
939     SJ037   SpiceJet    BLR         BOM 2026-04-17 19:14:41.701
940     SJ037   SpiceJet    BLR         BOM 2026-04-17 19:14:41.701
588     SJ118   SpiceJet    DEL         BOM 2026-04-19 01:08:41.702
589     SJ118   SpiceJet    DEL         BOM 2026-04-19 01:08:41.702
106     SJ142   SpiceJet    CCU         BOM 2026-04-20 15:14:41.702
105     SJ142   SpiceJet    CCU         BOM 2026-04-20 15:14:41.702
310     SJ146   SpiceJet    HYD         BLR 2026-04-19 22:37:41.702
309     SJ146   SpiceJet    HYD         BLR 2026-04-19 22:37:41.702
605     UK013    Vistara    BOM         MAA 2026-04-18 23:52:41.701
606     UK013    Vistara    BOM         MAA 2026-04-18 23:52:41.701
935     UK049    Vistara    HYD         BOM 2026-04-17 19:47:41.701
936     UK049    Vistara    HYD         BOM 2026-04-17 19:47:41.701
759     UK139        NaN    BLR         MAA 2026-04-18 10:54:41.703
758     UK139        NaN    BLR         MAA 2026-04-18 10:54:41.703
812     UK160    Vistara    BLR         BOM 2026-04-18 06:42:41.703
813     UK160    Vistara    BLR         BOM 2026-04-18 06:42:41.703
503     UK163    Vistara    DEL         HYD 2026-04-19 07:22:41.703
502     UK163    Vistara    DEL         HYD 2026-04-19 07:22:41.703
914     UK180    Vistara    CCU         MAA 2026-04-17 21:18:41.703
915     UK180    Vistara    CCU         MAA 2026-04-17 21:18:41.703

               arrival_time  duration
253 2026-04-20 07:30:41.701  04:04:00
270 2026-04-20 02:56:41.702  00:33:00
550 2026-04-19 06:21:41.701  02:28:00
549 2026-04-19 06:21:41.701  02:28:00
141 2026-04-20 16:11:41.701  03:06:00
142 2026-04-20 16:11:41.701  03:06:00
599 2026-04-19 04:37:41.701  04:09:00
598 2026-04-19 04:37:41.701  04:09:00
603 2026-04-19 01:44:41.702  01:39:00
602 2026-04-19 01:44:41.702  01:39:00
83  2026-04-20 17:43:41.704  01:02:00
84  2026-04-20 17:43:41.704  01:02:00
939 2026-04-17 22:31:41.701  03:17:00
940 2026-04-17 22:31:41.701  03:17:00
588 2026-04-19 02:33:41.702  01:25:00
589 2026-04-19 02:33:41.702  01:25:00
106 2026-04-20 16:56:41.702  01:42:00
105 2026-04-20 16:56:41.702  01:42:00
310 2026-04-20 00:33:41.702  01:56:00
309 2026-04-20 00:33:41.702  01:56:00
605 2026-04-19 02:52:41.701  03:00:00
606 2026-04-19 02:52:41.701  03:00:00
935 2026-04-17 20:32:41.701  00:45:00
936 2026-04-17 20:32:41.701  00:45:00
759 2026-04-18 14:31:41.703  03:37:00
758 2026-04-18 14:31:41.703  03:37:00
812 2026-04-18 10:58:41.703  04:16:00
813 2026-04-18 10:58:41.703  04:16:00
503 2026-04-19 09:04:41.703  01:42:00
502 2026-04-19 09:04:41.703  01:42:00
914 2026-04-17 23:29:41.703  02:11:00
915 2026-04-17 23:29:41.703  02:11:00
Duplicate booking IDs: 0
Duplicate passenger IDs: 39
Duplicate payment IDs: 0

---- DUPLICATE PASSENGER IDs -----
     passenger_id    first_name last_name  age gender  \
34          P1034        Ishaan      Iyer   62      M
35          P1034        Ishaan      Iyer   62      M
103         P1102          Myra  Kulkarni    1      F
104         P1102          Myra  Kulkarni    1      F
106         P1104        Vivaan     Verma   88      F
...           ...           ...       ...  ...    ...
1028        P1991         Aarav  Shhharma    4      F
1031        P1994          Diya  Kulkarni   89      F
1032        P1994  DiyaKulkarni       NaN   89      F
1037        P1999        Ananya    Pillai   14      F
1038        P1999  AnanyaPillai       NaN   14      F

                              email           phone    aadhaar_id  \
34          ishaan.iyer@outlook.com  +91-8679984033  122362316658
35            ishaan.iyer@gmail.com  +91-7994310083  669096705466
103    myra.kulkarni@rediffmail.com  +91-8128636900  606853615305
104       myra.kulkarni@outlook.com  +91-7247746438   47277901043
106          vivaan.verma@gmail.com  +91-7871531100  246095396218
...                             ...             ...           ...
1028  aarav.shhharma@rediffmail.com  +91-9196057919  645345472239
1031     diya.kulkarni1@hotmail.com  +91-7409498553  876230391114
1032    diyakulkarni.user@gmail.com  +91-9694250229  522823052480
1037       ananya.pillai2@yahoo.com  +91-9733969290  246320374767
1038  ananyapillai.user@outlook.com  +91-7597463844  260321450576

     date_of_birth
34      1964-08-14
35      1964-09-24
103     2025-02-27
104     2025-03-18
106     1938-06-03
...            ...
1028    2022-11-17
1031    1937-03-18
1032    1937-09-17
1037    2012-12-15
1038    2012-11-28

[75 rows x 9 columns]

In [ ]:
#Check flight time columns

print(flights[["flight_id", "departure_time", "arrival_time", "duration"]].head(10))

print("\nData types:")
print(flights[["departure_time", "arrival_time", "duration"]].dtypes)

  flight_id          departure_time            arrival_time  duration
0     SJ010 2026-04-20 23:38:41.701 2026-04-21 02:32:41.701  02:54:00
1     AI155 2026-04-20 23:35:41.703 2026-04-21 01:23:41.703  01:48:00
2     UK094 2026-04-20 23:26:41.702 2026-04-21 01:11:41.702  01:45:00
3     AI245 2026-04-20 23:07:41.704 2026-04-21 01:43:41.704  02:36:00
4     AI192 2026-04-20 23:05:41.703 2026-04-21 04:04:41.703  04:59:00
5     SJ158 2026-04-20 23:05:41.703 2026-04-21 01:24:41.703  02:19:00
6     6F196 2026-04-20 23:04:41.703 2026-04-21 00:47:41.703  01:43:00
7     AI080 2026-04-20 23:03:41.702 2026-04-21 00:35:41.702  01:32:00
8     6F025 2026-04-20 23:02:41.701 2026-04-20 23:57:41.701  00:55:00
9     6F251 2026-04-20 22:56:41.703 2026-04-20 23:37:41.703  00:41:00

Data types:
departure_time    datetime64[ns]
arrival_time      datetime64[ns]
duration                  object
dtype: object

In [ ]:
#Convert flight time to datetime

flights["departure_time"] = pd.to_datetime(
    flights["departure_time"],
    errors="coerce")

flights["arrival_time"] = pd.to_datetime(
    flights["arrival_time"],
    errors="coerce")

print(flights[["departure_time", "arrival_time"]].dtypes)

departure_time    datetime64[ns]
arrival_time      datetime64[ns]
dtype: object

In [ ]:
#Calculate duration from departure and arrival

flights["calculated_duration"] = (
    flights["arrival_time"] - flights["departure_time"])

flights["calculated_duration_hours"] = (
    flights["calculated_duration"].dt.total_seconds() / 3600)

display(
    flights[
        [
            "flight_id",
            "departure_time",
            "arrival_time",
            "calculated_duration_hours"
        ]].head(10))

,flight_id,departure_time,arrival_time,calculated_duration_hours
0,SJ010,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701,2.900000
1,AI155,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703,1.800000
2,UK094,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702,1.750000
3,AI245,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704,2.600000
4,AI192,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703,4.983333
5,SJ158,2026-04-20 23:05:41.703,2026-04-21 01:24:41.703,2.316667
6,6F196,2026-04-20 23:04:41.703,2026-04-21 00:47:41.703,1.716667
7,AI080,2026-04-20 23:03:41.702,2026-04-21 00:35:41.702,1.533333
8,6F025,2026-04-20 23:02:41.701,2026-04-20 23:57:41.701,0.916667
9,6F251,2026-04-20 22:56:41.703,2026-04-20 23:37:41.703,0.683333

In [ ]:
#Find negative durations

negative_duration = flights[
    flights["calculated_duration_hours"] < 0]

print("Number of negative durations:",
      len(negative_duration))

display(
    negative_duration[[
            "flight_id",
            "departure_time",
            "arrival_time",
            "calculated_duration_hours"]])

Number of negative durations: 1

,flight_id,departure_time,arrival_time,calculated_duration_hours
355,SJ192,2026-04-19 18:45:42,2026-04-18 23:45:42,-19.0

In [ ]:
#Compare existing duration with calculated duration

flights['duration'] = pd.to_timedelta(flights['duration'].astype(str), errors='coerce')

flights["existing_duration_hours"] = (
    flights["duration"].dt.total_seconds() / 3600)

flights["duration_difference"] = (
    flights["existing_duration_hours"]
    - flights["calculated_duration_hours"])

display(
    flights[[
            "flight_id",
            "existing_duration_hours",
            "calculated_duration_hours",
            "duration_difference"]].head(10))

,flight_id,existing_duration_hours,calculated_duration_hours,duration_difference
0,SJ010,2.900000,2.900000,0.0
1,AI155,1.800000,1.800000,0.0
2,UK094,1.750000,1.750000,0.0
3,AI245,2.600000,2.600000,0.0
4,AI192,4.983333,4.983333,0.0
5,SJ158,2.316667,2.316667,0.0
6,6F196,1.716667,1.716667,0.0
7,AI080,1.533333,1.533333,0.0
8,6F025,0.916667,0.916667,0.0
9,6F251,0.683333,0.683333,0.0

In [ ]:
#Find duration mismatches

duration_mismatch = flights[
    flights["duration_difference"].abs() > 0.01]
print("Number of duration mismatches:", len(duration_mismatch))
display(duration_mismatch)

Number of duration mismatches: 0

Empty DataFrame
Columns: [flight_id, airline, source, destination, departure_time, arrival_time, duration, calculated_duration, calculated_duration_hours, existing_duration_hours, duration_difference]
Index: []

In [ ]:
# Check negative durations

negative_duration = flights[
    flights["calculated_duration_hours"] < 0]
print("Number of negative durations:", len(negative_duration))
display(
    negative_duration[[
            "flight_id",
            "departure_time",
            "arrival_time",
            "calculated_duration_hours",
            "existing_duration_hours"]])

Number of negative durations: 1

,flight_id,departure_time,arrival_time,calculated_duration_hours,existing_duration_hours
355,SJ192,2026-04-19 18:45:42,2026-04-18 23:45:42,-19.0,NaN

In [ ]:
#Handle overnight flight

flights["corrected_arrival_time"] = flights["arrival_time"]
overnight = flights["arrival_time"] < flights["departure_time"]
flights.loc[overnight, "corrected_arrival_time"] = (
    flights.loc[overnight, "arrival_time"] + pd.Timedelta(days=1))

flights["corrected_duration_hours"] = (
    flights["corrected_arrival_time"]
    - flights["departure_time"]).dt.total_seconds() / 3600

display(
    flights[overnight][[
            "flight_id",
            "departure_time",
            "arrival_time",
            "corrected_arrival_time",
            "corrected_duration_hours"]])

,flight_id,departure_time,arrival_time,corrected_arrival_time,corrected_duration_hours
355,SJ192,2026-04-19 18:45:42,2026-04-18 23:45:42,2026-04-19 23:45:42,5.0

In [ ]:
#Validate corrected duration

negative_after_correction = flights[
    flights["corrected_duration_hours"] < 0]

print("Negative durations after correction:",len(negative_after_correction))
display(
    negative_after_correction[[
            "flight_id",
            "departure_time",
            "arrival_time",
            "corrected_duration_hours"]])

Negative durations after correction: 0

Empty DataFrame
Columns: [flight_id, departure_time, arrival_time, corrected_duration_hours]
Index: []

In [ ]:
#Missing value analysis

datasets = {
    "Flights": flights,
    "Bookings": bookings,
    "Payments": payments,
    "Passengers": passengers}

for name, df in datasets.items():
    print(f"\n----{name}----")
    missing = df.isnull().sum()
    percentage = (missing / len(df)) * 100

    result = pd.DataFrame({
        "Missing Values": missing,
        "Missing Percentage": percentage.round(2)})

    display(result[result["Missing Values"] > 0])

===== Flights =====

                         Missing Values  Missing Percentage
airline                              41                4.02
duration                              1                0.10
existing_duration_hours               1                0.10
duration_difference                   1                0.10

===== Bookings =====

        Missing Values  Missing Percentage
status              45                 4.5

===== Payments =====

        Missing Values  Missing Percentage
amount              48                 4.8

===== Passengers =====

           Missing Values  Missing Percentage
last_name              10                0.96

In [ ]:
#Check booking status
print(bookings["status"].value_counts(dropna=False))

status
CONFIRMED    320
CANCELLED    314
PENDING      291
NaN           45
INVALID       30
Name: count, dtype: int64

In [ ]:
#Check payment amounts

print(payments["amount"].dtype)
print("\nNon-numeric amounts:")
print(payments[
    pd.to_numeric(payments["amount"], errors="coerce").isna()]["amount"].value_counts(dropna=False))

object

Non-numeric amounts:
amount
NaN        48
INVALID    30
Name: count, dtype: int64

In [ ]:
#Create numeric payment amount
payments["amount_numeric"] = pd.to_numeric(
    payments["amount"],
    errors="coerce")
display(payments[["amount", "amount_numeric"]].head(10))

     amount  amount_numeric
0   9883.49         9883.49
1   8457.96         8457.96
2   6495.37         6495.37
3   5079.38         5079.38
4  12518.31        12518.31
5   7319.71         7319.71
6   8020.26         8020.26
7    8291.6         8291.60
8   7277.14         7277.14
9   4585.24         4585.24

In [ ]:
#Passenger ID duplicate analysis

duplicate_passenger_ids = passengers[passengers["passenger_id"].duplicated(keep=False)]
print("Rows having duplicate passenger IDs:",len(duplicate_passenger_ids))
display(duplicate_passenger_ids.sort_values("passenger_id").head(20))

Rows having duplicate passenger IDs: 75

,passenger_id,first_name,last_name,age,gender,email,phone,aadhaar_id,date_of_birth
34,P1034,Ishaan,Iyer,62,M,ishaan.iyer@outlook.com,+91-8679984033,122362316658,1964-08-14
35,P1034,Ishaan,Iyer,62,M,ishaan.iyer@gmail.com,+91-7994310083,669096705466,1964-09-24
103,P1102,Myra,Kulkarni,1,F,myra.kulkarni@rediffmail.com,+91-8128636900,606853615305,2025-02-27
104,P1102,Myra,Kulkarni,1,F,myra.kulkarni@outlook.com,+91-7247746438,47277901043,2025-03-18
106,P1104,Vivaan,Verma,88,F,vivaan.verma@gmail.com,+91-7871531100,246095396218,1938-06-03
107,P1104,Vivaan,Verma,88,F,vivaan.verma@hotmail.com,+91-6519246503,706540515319,1938-12-25
108,P1104,Vivaan,Verma,88,F,vivaan.verma@outlook.com,+91-7147605080,585277221704,1938-04-02
113,P1108,IshaanKulkarni,NaN,8,M,ishaankulkarni.user@outlook.com,+91-8511086777,909275571928,2018-06-13
112,P1108,Ishaan,Kulkarni,8,M,ishaan.kulkarni@outlook.com,+91-9394801573,16582029702,2018-02-08
145,P1140,Shaurya,Singh,42,M,shaurya.singh@outlook.com,+91-6525146690,403910651801,1984-08-02
146,P1140,Shaurya,Singh,42,M,shaurya.singh1@outlook.com,+91-9293253475,265676618251,1984-03-18
147,P1141,Sai,Kulkarni,77,M,sai.kulkarni@rediffmail.com,+91-7881531720,300478686337,1949-06-05
148,P1141,SaiKulkarni,NaN,77,M,saikulkarni.user@outlook.com,+91-7878488534,106903311907,1949-10-22
185,P1178,Kavya,Naidu,72,M,kavya.naidu@outlook.com,+91-8682014641,78361340745,1954-02-15
186,P1178,Kavyanaidu,NaN,72,M,kavyanaidu.user@gmail.com,+91-7325354965,959629233095,1954-09-09
225,P1216,Riya,Sharma,56,F,riya.sharma@hotmail.com,+91-9208908082,793271040541,1970-02-11
224,P1216,Riya,Sharma,56,F,riya.sharma@outlook.com,+91-7367942460,154100676267,1970-07-12
246,P1236,MyraSharma,NaN,20,F,myrasharma.user@outlook.com,+91-6338642889,534655494717,2006-01-28
245,P1236,Myra,Sharma,20,F,myra.sharma@yahoo.com,+91-9821413281,584282417248,2006-03-22
262,P1252,Aadhya,Agarwal,16,M,aadhya.agarwal@rediffmail.com,+91-7987380851,890028772175,2010-04-11

In [ ]:
#Exact duplicate analysis

print("Flights:", flights.duplicated().sum())
print("Bookings:", bookings.duplicated().sum())
print("Payments:", payments.duplicated().sum())
print("Passengers:", passengers.duplicated().sum())

In [ ]:
#Validate booking flight IDs

print("\n----Check booking → flight----")
missing_flights = bookings[~bookings["flight_id"].isin(flights["flight_id"])]
print("Booking records with missing flight IDs:",len(missing_flights))


print("\n-----Check booking → passenger-----")
missing_passengers = bookings[~bookings["passenger_id"].isin(passengers["passenger_id"])]
print("Booking records with missing passenger IDs:",len(missing_passengers))


print("\n----Check payment → booking------")
missing_bookings = payments[~payments["booking_id"].isin(bookings["booking_id"])]
print("Payment records with missing booking IDs:",len(missing_bookings))

----Check booking → flight----
Booking records with missing flight IDs: 0

-----Check booking → passenger-----
Booking records with missing passenger IDs: 0

----Check payment → booking------
Payment records with missing booking IDs: 0

In [ ]:
#Identify PII columns

print("Passenger PII columns:")
print([
    "first_name",
    "last_name",
    "email",
    "phone",
    "aadhaar_id",
    "date_of_birth"])

print("\nBooking PII columns:")
print([
    "passport_number",
    "emergency_contact_name",
    "emergency_contact_phone"])

Passenger PII columns:
['first_name', 'last_name', 'email', 'phone', 'aadhaar_id', 'date_of_birth']

Booking PII columns:
['passport_number', 'emergency_contact_name', 'emergency_contact_phone']

In [ ]:
#Check Aadhaar ID lengths

aadhaar_length = passengers["aadhaar_id"].astype(str).str.len()
print(aadhaar_length.value_counts().sort_index())

aadhaar_id
10      5
11    109
12    925
Name: count, dtype: int64

In [ ]:
#Data quality summary

quality_summary = pd.DataFrame({
    "Dataset": ["Flights", "Bookings", "Payments", "Passengers"],
    "Rows": [
        len(flights),
        len(bookings),
        len(payments),
        len(passengers)],
    "Columns": [
        flights.shape[1],
        bookings.shape[1],
        payments.shape[1],
        passengers.shape[1]],
    "Missing Values": [
        flights.isnull().sum().sum(),
        bookings.isnull().sum().sum(),
        payments.isnull().sum().sum(),
        passengers.isnull().sum().sum()],
    "Duplicate Rows": [
        flights.duplicated().sum(),
        bookings.duplicated().sum(),
        payments.duplicated().sum(),
        passengers.duplicated().sum()]})
display(quality_summary)

      Dataset  Rows  Columns  Missing Values  Duplicate Rows
0     Flights  1020       13              44              15
1    Bookings  1000        9              45               0
2    Payments  1000        5             126               0
3  Passengers  1039        9              10               0

In [ ]:
#Remove exact duplicate rows

flights = flights.drop_duplicates().reset_index(drop=True)
bookings = bookings.drop_duplicates().reset_index(drop=True)
payments = payments.drop_duplicates().reset_index(drop=True)
passengers = passengers.drop_duplicates().reset_index(drop=True)

print("Duplicate rows after cleaning:")
print("Flights:", flights.duplicated().sum())
print("Bookings:", bookings.duplicated().sum())
print("Payments:", payments.duplicated().sum())
print("Passengers:", passengers.duplicated().sum())

Duplicate rows after cleaning:
Flights: 0
Bookings: 0
Payments: 0
Passengers: 0

In [ ]:
#Clean airline values

flights["airline"] = flights["airline"].fillna("Unknown")
flights["airline"] = flights["airline"].replace(
    "UNKNOWN", "Unknown")
print(flights["airline"].value_counts())

airline
IndiGo       249
SpiceJet     236
Air India    233
Vistara      218
Unknown       69
Name: count, dtype: int64

In [ ]:
# Step 33: Clean booking status

valid_status = ["CONFIRMED", "CANCELLED", "PENDING"]
bookings["status"] = bookings["status"].where(
    bookings["status"].isin(valid_status),
    "UNKNOWN")
print(bookings["status"].value_counts())

#Check invalid payment amounts
print("\nInvalid or missing payment amounts:",payments["amount_numeric"].isna().sum())

status
CONFIRMED    320
CANCELLED    314
PENDING      291
UNKNOWN       75
Name: count, dtype: int64

Invalid or missing payment amounts: 78

In [ ]:
#Check valid payment amounts

print("Minimum payment amount:",payments["amount_numeric"].min())
print("Maximum payment amount:",payments["amount_numeric"].max())
print("Missing payment amounts:",payments["amount_numeric"].isna().sum())

Minimum payment amount: 1002.59
Maximum payment amount: 14992.95
Missing payment amounts: 78

In [ ]:
#Create final flight duration

flights["flight_duration_hours"] = (
    flights["corrected_duration_hours"])
print(flights[["flight_id", "flight_duration_hours"]].head(10))

  flight_id  flight_duration_hours
0     SJ010               2.900000
1     AI155               1.800000
2     UK094               1.750000
3     AI245               2.600000
4     AI192               4.983333
5     SJ158               2.316667
6     6F196               1.716667
7     AI080               1.533333
8     6F025               0.916667
9     6F251               0.683333

In [ ]:
#Create flight analysis features

flights["route"] = (flights["source"] + " → " + flights["destination"])
flights["departure_date"] = (flights["departure_time"].dt.date)
flights["departure_hour"] = (flights["departure_time"].dt.hour)
flights["departure_day"] = (flights["departure_time"].dt.day_name())
flights["departure_month"] = (flights["departure_time"].dt.month_name())
flights["overnight_flag"] = (flights["arrival_time"] < flights["departure_time"])
display(
    flights[[
            "flight_id",
            "route",
            "flight_duration_hours",
            "departure_hour",
            "departure_day",
            "departure_month",
            "overnight_flag"]].head(10))

,flight_id,route,flight_duration_hours,departure_hour,departure_day,departure_month,overnight_flag
0,SJ010,CCU → MAA,2.900000,23,Monday,April,False
1,AI155,BOM → CCU,1.800000,23,Monday,April,False
2,UK094,BOM → CCU,1.750000,23,Monday,April,False
3,AI245,BOM → CCU,2.600000,23,Monday,April,False
4,AI192,MAA → BOM,4.983333,23,Monday,April,False
5,SJ158,DEL → HYD,2.316667,23,Monday,April,False
6,6F196,CCU → MAA,1.716667,23,Monday,April,False
7,AI080,BOM → HYD,1.533333,23,Monday,April,False
8,6F025,BLR → BOM,0.916667,23,Monday,April,False
9,6F251,DEL → BLR,0.683333,22,Monday,April,False

In [ ]:
#Validate final flight data

print("Total flights:", len(flights))
print("Negative final durations:",(flights["flight_duration_hours"] < 0).sum())
print("Missing final durations:",flights["flight_duration_hours"].isna().sum())
print("Missing routes:",flights["route"].isna().sum())

Total flights: 1005
Negative final durations: 0
Missing final durations: 0
Missing routes: 0

In [ ]:
#Passenger cleaning
# Remove only exact duplicate rows
passengers = passengers.drop_duplicates().reset_index(drop=True)
# Fill missing names
passengers["first_name"] = passengers["first_name"].fillna("Unknown")
passengers["last_name"] = passengers["last_name"].fillna("Unknown")
print("Passenger rows after removing exact duplicates:", len(passengers))
display(passengers.head())

Passenger rows after removing exact duplicates: 1039

,passenger_id,first_name,last_name,age,gender,email,phone,aadhaar_id,date_of_birth
0,P1000,Vivaan,Chatterjee,52,F,vivaan.chatterjee@gmail.com,+91-6896233790,433218196001,1974-04-08
1,P1001,Krishna,Reddy,15,M,krishna.reddy@hotmail.com,+91-6702632297,386379402654,2011-03-07
2,P1002,Myra,Naidu,72,M,myra.naidu@outlook.com,+91-6199585092,615594078161,1954-09-10
3,P1003,Myra,Mishra,61,F,myra.mishra@hotmail.com,+91-8719927151,310341316475,1965-03-12
4,P1004,Saanvi,Banerjee,21,M,saanvi.banerjee@outlook.com,+91-7819595113,419283276483,2005-11-11

In [ ]:
#Mask Passenger PII

passengers["email_masked"] = passengers["email"].astype(str).str.replace(
    r"(^.).*(@.*$)", r"\1***\2", regex=True)

passengers["phone_masked"] = passengers["phone"].astype(str).apply(
    lambda x: "***" + x[-4:] if x != "nan" else "Unknown")

passengers["aadhaar_masked"] = passengers["aadhaar_id"].astype(str).apply(
    lambda x: "********" + x[-4:] if x != "nan" else "Unknown")

display(passengers[
    ["passenger_id", "first_name", "last_name",
     "email_masked", "phone_masked", "aadhaar_masked"]].head())

,passenger_id,first_name,last_name,email_masked,phone_masked,aadhaar_masked
0,P1000,Vivaan,Chatterjee,v***@gmail.com,***3790,********6001
1,P1001,Krishna,Reddy,k***@hotmail.com,***2297,********2654
2,P1002,Myra,Naidu,m***@outlook.com,***5092,********8161
3,P1003,Myra,Mishra,m***@hotmail.com,***7151,********6475
4,P1004,Saanvi,Banerjee,s***@outlook.com,***5113,********6483

In [ ]:

#Clean Booking Status

valid_status = ["CONFIRMED", "CANCELLED", "PENDING"]
bookings["status_clean"] = bookings["status"].where(bookings["status"].isin(valid_status),"UNKNOWN")
print(bookings["status_clean"].value_counts())

status_clean
CONFIRMED    320
CANCELLED    314
PENDING      291
UNKNOWN       75
Name: count, dtype: int64

In [ ]:
#Convert payment amount to numeric

payments["amount_numeric"] = pd.to_numeric(payments["amount"],errors="coerce")
print("Missing/Invalid payment amounts:",payments["amount_numeric"].isna().sum())
display(payments.head())

Missing/Invalid payment amounts: 78

  payment_id booking_id    amount payment_method  amount_numeric
0    PAY1000      B1116   9883.49     NETBANKING         9883.49
1    PAY1001      B1738   8457.96     NETBANKING         8457.96
2    PAY1002      B1873   6495.37            UPI         6495.37
3    PAY1003      B1914   5079.38     NETBANKING         5079.38
4    PAY1004      B1967  12518.31           CARD        12518.31

In [ ]:
#Referential Integrity Validation

invalid_booking_flights = bookings[~bookings["flight_id"].isin(flights["flight_id"])]
invalid_booking_passengers = bookings[~bookings["passenger_id"].isin(passengers["passenger_id"])]
invalid_payment_bookings = payments[~payments["booking_id"].isin(bookings["booking_id"])]

print("Invalid booking-flight relationships:", len(invalid_booking_flights))
print("Invalid booking-passenger relationships:", len(invalid_booking_passengers))
print("Invalid payment-booking relationships:", len(invalid_payment_bookings))

Invalid booking-flight relationships: 0
Invalid booking-passenger relationships: 0
Invalid payment-booking relationships: 0

In [ ]:
#Airline KPI

airline_kpi = flights.groupby("airline").agg(
    Total_Flights=("flight_id", "count"),
    Average_Duration_Hours=("flight_duration_hours", "mean")).reset_index()
airline_kpi["Average_Duration_Hours"] = (airline_kpi["Average_Duration_Hours"].round(2))
display(airline_kpi)

     airline  Total_Flights  Average_Duration_Hours
0  Air India            233                    2.72
1     IndiGo            249                    2.80
2   SpiceJet            236                    2.74
3    Unknown             69                    2.77
4    Vistara            218                    2.71

In [ ]:
#Route KPI

route_kpi = flights.groupby("route").agg(
    Total_Flights=("flight_id", "count"),
    Average_Duration_Hours=("flight_duration_hours", "mean")).reset_index()
route_kpi["Average_Duration_Hours"] = (
    route_kpi["Average_Duration_Hours"].round(2))
route_kpi = route_kpi.sort_values(
    "Total_Flights",
    ascending=False)
display(route_kpi.head(10))

        route  Total_Flights  Average_Duration_Hours
6   BOM → CCU             90                    2.83
12  CCU → DEL             72                    2.56
25  MAA → BLR             65                    2.88
0   BLR → BOM             60                    2.46
24  HYD → MAA             57                    2.55
18  DEL → HYD             54                    2.91
23  HYD → DEL             42                    3.09
7   BOM → DEL             39                    2.56
11  CCU → BOM             33                    2.73
15  DEL → BLR             29                    2.83

In [ ]:
#Booking KPI

booking_kpi = bookings.groupby("status_clean").size().reset_index(name="Total_Bookings")
display(booking_kpi)

print("\n-----payment KPI----")
payment_kpi = payments.groupby("payment_method").agg(
    Total_Transactions=("payment_id", "count"),
    Total_Amount=("amount_numeric", "sum")).reset_index()
payment_kpi["Total_Amount"] = payment_kpi["Total_Amount"].round(2)
display(payment_kpi)

  status_clean  Total_Bookings
0    CANCELLED             314
1    CONFIRMED             320
2      PENDING             291
3      UNKNOWN              75

-----payment KPI----

  payment_method  Total_Transactions  Total_Amount
0           CARD                 329    2400812.04
1     NETBANKING                 313    2365644.17
2            UPI                 358    2618686.77

In [ ]:
#Create safe Passenger table for reporting

passengers_report = passengers[[
        "passenger_id",
        "first_name",
        "last_name",
        "age",
        "gender",
        "email_masked",
        "phone_masked",
        "aadhaar_masked"]].copy()
display(passengers_report.head())

,passenger_id,first_name,last_name,age,gender,email_masked,phone_masked,aadhaar_masked
0,P1000,Vivaan,Chatterjee,52,F,v***@gmail.com,***3790,********6001
1,P1001,Krishna,Reddy,15,M,k***@hotmail.com,***2297,********2654
2,P1002,Myra,Naidu,72,M,m***@outlook.com,***5092,********8161
3,P1003,Myra,Mishra,61,F,m***@hotmail.com,***7151,********6475
4,P1004,Saanvi,Banerjee,21,M,s***@outlook.com,***5113,********6483

In [ ]:
#Create safe Booking table for reporting

bookings_report = bookings[[
        "booking_id",
        "passenger_id",
        "flight_id",
        "booking_date",
        "status_clean",
        "seat_number"]].copy()
display(bookings_report.head())

In [ ]:
#Final Pipeline Validation

#Create safe Booking table
bookings_report = bookings[[
        "booking_id",
        "passenger_id",
        "flight_id",
        "booking_date",
        "status_clean",
        "seat_number"]].copy()

#Create safe Passenger table
passengers_report = passengers[[
        "passenger_id",
        "first_name",
        "last_name",
        "age",
        "gender",
        "email_masked",
        "phone_masked",
        "aadhaar_masked"]].copy()

print("------ FINAL DATA VALIDATION ------")

print("Flights:", len(flights))
print("Bookings:", len(bookings_report))
print("Payments:", len(payments))
print("Passengers:", len(passengers_report))

print("\nNegative flight durations:",
      (flights["flight_duration_hours"] < 0).sum())

print("Missing flight durations:",
      flights["flight_duration_hours"].isna().sum())

print("Missing numeric payments:",
      payments["amount_numeric"].isna().sum())

print("\nPipeline validation completed.")

------ FINAL DATA VALIDATION ------
Flights: 1005
Bookings: 1000
Payments: 1000
Passengers: 1039

Negative flight durations: 0
Missing flight durations: 0
Missing numeric payments: 78

Pipeline validation completed.

In [ ]:
#Check exported files

import os
files = [
    "clean_flights.csv",
    "clean_bookings.csv",
    "clean_payments.csv",
    "clean_passengers.csv",
    "airline_kpi.csv",
    "route_kpi.csv",
    "booking_kpi.csv",
    "payment_kpi.csv"]
for file in files:
    path = "/content/" + file
    print(file, "->", "Created" if os.path.exists(path) else "Missing")

clean_flights.csv -> Created
clean_bookings.csv -> Created
clean_payments.csv -> Created
clean_passengers.csv -> Created
airline_kpi.csv -> Created
route_kpi.csv -> Created
booking_kpi.csv -> Created
payment_kpi.csv -> Created